CREATE OR REPLACE PROCEDURE SH_GOLD.SP_LOAD_GOLD_KPIS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

INSERT INTO SH_GOLD.FRAUD_PROBABILITY_SCORE
SELECT
account_id,
COUNT(*) AS total_txns,
SUM(CASE WHEN amount > 50000 THEN 1 ELSE 0 END) AS high_value_txns,
CASE
WHEN SUM(CASE WHEN amount > 50000 THEN 1 ELSE 0 END) > 3
THEN 'HIGH_RISK'
ELSE 'NORMAL'
END,
CURRENT_TIMESTAMP
FROM SH_SILVER.SILVER_TRANSACTIONS_MASTER
GROUP BY account_id;

INSERT INTO SH_GOLD.CUSTOMER_CREDIT_RISK
SELECT
a.customer_id,
a.phone,
AVG(a.credit_score),
COUNT(l.loan_id),
CASE
WHEN AVG(a.credit_score) < 600 THEN 'HIGH_RISK'
WHEN AVG(a.credit_score) BETWEEN 600 AND 700 THEN 'MEDIUM_RISK'
ELSE 'LOW_RISK'
END,
CURRENT_TIMESTAMP
FROM SH_SILVER.SILVER_ACCOUNTS_MASTER a
LEFT JOIN SH_SILVER.SILVER_LOANS_MASTER l
ON a.customer_id = l.customer_id
GROUP BY a.customer_id, a.phone;

INSERT INTO SH_GOLD.SAVINGS_ACTIVITY_RATIO
SELECT
t.account_id,
COUNT(*),
SUM(t.amount),
CASE
WHEN COUNT(*) > 50 THEN 'HIGH_ACTIVITY'
WHEN COUNT(*) BETWEEN 20 AND 50 THEN 'MEDIUM_ACTIVITY'
ELSE 'LOW_ACTIVITY'
END,
CURRENT_TIMESTAMP
FROM SH_SILVER.SILVER_TRANSACTIONS_MASTER t
JOIN SH_SILVER.SILVER_ACCOUNTS_MASTER a
ON t.account_id = a.account_id
WHERE a.account_type = 'SAVINGS'
GROUP BY t.account_id;

INSERT INTO SH_GOLD.LOAN_HEALTH_INDEX
SELECT
loan_id,
customer_id,
principal_amount,
dpd_days,
CASE
WHEN dpd_days > 30 THEN 'DELINQUENT'
ELSE 'HEALTHY'
END,
CURRENT_TIMESTAMP
FROM SH_SILVER.SILVER_LOANS_MASTER;

INSERT INTO SH_GOLD.CHANNEL_ATV
SELECT
channel,
COUNT(*),
AVG(amount),
CURRENT_TIMESTAMP
FROM SH_SILVER.SILVER_TRANSACTIONS_MASTER
GROUP BY channel;

RETURN 'GOLD KPIs LOADED';

END;

$$;

CALL SH_GOLD.SP_LOAD_GOLD_KPIS();
