CREATE OR REPLACE DATABASE HACKATHON_DB;
CREATE ROLE HACKATHON_ROLE;
GRANT USAGE ON DATABASE HACKATHON_DB TO ROLE HACKATHON_ROLE;

GRANT ALL PRIVILEGES ON DATABASE HACKATHON_DB TO ROLE +HACKATHON_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE HACKATHON_DB TO ROLE HACKATHON_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE HACKATHON_DB TO ROLE HACKATHON_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE HACKATHON_DB TO ROLE HACKATHON_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE HACKATHON_DB TO ROLE HACKATHON_ROLE;

GRANT ALL PRIVILEGES ON ALL STAGES IN DATABASE HACKATHON_DB TO ROLE HACKATHON_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN DATABASE HACKATHON_DB TO ROLE HACKATHON_ROLE;