CREATE OR REPLACE VIEW SH_GOLD.VW_FRAUD_DASHBOARD AS
SELECT
account_id,
total_txns,
high_value_txns,
fraud_risk_level,
load_timestamp
FROM SH_GOLD.FRAUD_PROBABILITY_SCORE;

GRANT SELECT ON VIEW SH_GOLD.VW_FRAUD_DASHBOARD
TO ROLE FRAUD_ANALYST_ROLE;