CREATE OR REPLACE VIEW SH_GOLD.VW_BUSINESS_DASHBOARD AS
SELECT
s.account_id,
s.activity_level,
c.channel,
c.avg_transaction_value,
s.load_timestamp
FROM SH_GOLD.SAVINGS_ACTIVITY_RATIO s
LEFT JOIN SH_GOLD.CHANNEL_ATV c
ON 1=1;

GRANT SELECT ON VIEW SH_GOLD.VW_BUSINESS_DASHBOARD
TO ROLE BUSINESS_ANALYST_ROLE;