CREATE ROLE FRAUD_ANALYST_ROLE;
CREATE ROLE RISK_MANAGER_ROLE;
CREATE ROLE BUSINESS_ANALYST_ROLE;

GRANT USAGE ON DATABASE HACKATHON_DB TO ROLE FRAUD_ANALYST_ROLE;
GRANT USAGE ON DATABASE HACKATHON_DB TO ROLE RISK_MANAGER_ROLE;
GRANT USAGE ON DATABASE HACKATHON_DB TO ROLE BUSINESS_ANALYST_ROLE;

GRANT USAGE ON SCHEMA SH_GOLD TO ROLE FRAUD_ANALYST_ROLE;
GRANT USAGE ON SCHEMA SH_GOLD TO ROLE RISK_MANAGER_ROLE;
GRANT USAGE ON SCHEMA SH_GOLD TO ROLE BUSINESS_ANALYST_ROLE;