CREATE OR REPLACE MASKING POLICY SH_GOLD.MASK_PHONE_NUMBER
AS (phone_val NUMBER)
RETURNS NUMBER ->
CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','SYSADMIN')
        THEN phone_val
    ELSE
        MOD(phone_val, 10000)
END;