CREATE OR REPLACE FILE FORMAT file_csv
    TYPE = csv
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = true
    ERROR_ON_COLUMN_COUNT_MISMATCH = true
    NULL_IF = ('NULL','null')
    SKIP_BLANK_LINES = true
    TYPE=CSV,
    FIELD_DELIMITER=',',
    REPLACE_INVALID_CHARACTERS=TRUE,
    DATE_FORMAT=AUTO,
    TIME_FORMAT=AUTO,
    TIMESTAMP_FORMAT=AUTO
;

DESC FILE FORMAT file_csv;