CREATE OR REPLACE TABLE SH_GOLD.FRAUD_PROBABILITY_SCORE
(
    ACCOUNT_ID STRING,
    TOTAL_TXNS NUMBER,
    HIGH_VALUE_TXNS NUMBER,
    FRAUD_RISK_LEVEL STRING,
    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);