CREATE OR REPLACE TABLE SH_GOLD.CUSTOMER_CREDIT_RISK
(
    CUSTOMER_ID STRING,
    PHONE_NUMBER number,
    AVG_CREDIT_SCORE NUMBER,
    TOTAL_LOANS NUMBER,
    RISK_CATEGORY STRING,
    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);