CREATE OR REPLACE TABLE SH_GOLD.SAVINGS_ACTIVITY_RATIO
(
    ACCOUNT_ID STRING,
    TXN_COUNT NUMBER,
    TOTAL_AMOUNT NUMBER,
    ACTIVITY_LEVEL STRING,
    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);