CREATE OR REPLACE TABLE SH_GOLD.LOAN_HEALTH_INDEX
(
    LOAN_ID STRING,
    CUSTOMER_ID STRING,
    PRINCIPAL_AMOUNT NUMBER,
    DPD_DAYS NUMBER,
    LOAN_STATUS STRING,
    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);